spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassname: org.h2.Driver


jwt:
  secret: conunSecretKey
  expiration: 86400000
  auth:
    facebook: https://graph.facebook.com/me?fields=email,first_name,last_name&access_token=%s
    google: https://www.googleapis.com/oauth2/v1/userinfo?alt=json&access_token=%s&scope=https://www.googleapis.com/auth/userinfo.email

